// GENERATED by getzure-client-service (cmd/genrules). Do not edit by hand.
// Change internal/validation/rules.go there, then run the generator again.

export const THAI_NAME_PATTERN = /^[ก-ฺเ-๎\s]+$/u
export const ENGLISH_NAME_PATTERN = /^[A-Za-z\s]+$/u
export const BANK_ACCOUNT_NO_PATTERN = /^\d{10,12}$/u
export const NATIONAL_ID_PATTERN = /^\d{13}$/u
export const POSTCODE_PATTERN = /^\d{5}$/u
export const ADDRESS_TEXT_PATTERN = /^[\p{L}\p{M}\p{N}\s./,()-]+$/u

export const NAME_MAX_LENGTH = 100
export const HOUSE_NO_MAX_LENGTH = 30
export const STREET_MAX_LENGTH = 100
export const AREA_NAME_MAX_LENGTH = 60
export const KYC_IMAGE_MAX_BYTES = 5242880

export const BANK_CODES = [
	"kbank",
	"scb",
	"bbl",
	"ktb",
	"bay",
	"ttb",
	"gsb",
	"baac",
	"cimb",
	"uob",
] as const

export type TBankCode = (typeof BANK_CODES)[number]

export const KYC_IMAGE_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"]
