import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/app/components/QueryProvider";
import { Toaster } from "@/app/components/Toaster";

const notoSansThai = Noto_Sans_Thai({
	variable: "--font-noto-sans-thai",
	subsets: ["thai"],
	weight: ["300", "500", "700"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const themeInitScript = `(function () {
	try {
		var storedTheme = localStorage.getItem("theme");
		var isDark = storedTheme
			? storedTheme === "dark"
			: window.matchMedia("(prefers-color-scheme: dark)").matches;
		document.documentElement.classList.toggle("dark", isDark);

		var storedLang = localStorage.getItem("lang");
		document.documentElement.lang = storedLang === "th" ? "th" : "en";
	} catch (e) {}
})();`

const RootLayout = ({ children }: LayoutProps<"/">) => {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={`${notoSansThai.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
				<QueryProvider>{children}</QueryProvider>
				<Toaster />
			</body>
		</html>
	)
}

export default RootLayout
